# Generated by Django 5.2.7 on 2025-11-07 00:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('Id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Ciudad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_Estado', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoEnvio',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('MetodoEnvio', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Metodo', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefono', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('FNacimiento', models.DateField()),
                ('IdCiudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialBusqueda',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Busqueda', models.CharField(max_length=255)),
                ('FechaBusqueda', models.DateTimeField()),
                ('IdCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('FechaPedido', models.DateField()),
                ('Total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('IdCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.cliente')),
                ('IdEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.estado')),
                ('IdMetodoEnvio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.metodoenvio')),
                ('IdMetodoPago', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('IdCategoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('IdPedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.pedido')),
                ('IdProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Reseña',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Calificacion', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('Descripcion', models.CharField(max_length=255, null=True)),
                ('Fecha', models.DateTimeField()),
                ('IdCliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.cliente')),
                ('IdProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Nombres', models.CharField(max_length=50)),
                ('Apellidos', models.CharField(max_length=50)),
                ('NombreNegocio', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Telefono', models.CharField(max_length=8, unique=True, validators=[django.core.validators.MinValueValidator(10000000), django.core.validators.MaxValueValidator(99999999)])),
                ('FNacimiento', models.DateField()),
                ('IdCiudad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.ciudad')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='IdVendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.vendedor'),
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=100)),
                ('Cantidad', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('IdEstado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.estado')),
                ('IdProducto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.producto')),
                ('IdVendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='NicaGrow.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='CredencialVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NicaGrow.vendedor')),
                ('id_Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CredencialCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NicaGrow.cliente')),
                ('id_Usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
